# Generated by Django 5.2.6 on 2025-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
