# Generated by Django 5.2.6 on 2025-09-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
